### ISSUE TITLE
may be a bug?

### ISSUE THREAD

**Issue by realchen** [gi097/json_parser#2]
hi
may be I find a problem
after you fix the bug ,I run all the code ok
but today when  I try to run release mode,it occurs some mistake,
all the code are ok in debug mode
then,I write a demo and confirm the issue
here is some StackTrace,would you please see this?
```
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Station' in type cast
E/flutter ( 3984): #0      _CastListBase.[] (dart:_internal/cast.dart:99)
E/flutter ( 3984): #1      _MyHomePageState.parseStationListJson (file:///E:/FlutterProjects/flutter_testjson/lib/main.dart:148)
E/flutter ( 3984): #2      _MyHomePageState.getStationList.<anonymous closure> (file:///E:/FlutterProjects/flutter_testjson/lib/main.dart:136)

```

**Comment by gi097** [comment]
Closing this issue as there is no reply.

**Comment by realchen** [comment]
sorry for reply so late 
the class is :
```
import 'package:json_parser/reflectable.dart';

@reflectable
class StationListModel {
  String result = "";
  String msg = "";
  List<Station> _list = [];

  List<Station> get data => _list;

  set data(List list) {
    _list = list.cast<Station>();
  }
}

@reflectable
class Station {
  bool isSelect = false;
  String address = "";
  String id = "";
  String name = "";
}

```
and the json input is ：
```
{
I/flutter (31095):     "msg": "success",
I/flutter (31095):     "result": "1",
I/flutter (31095):     "data": [
I/flutter (31095):         {
I/flutter (31095):             "isSelect": true,
I/flutter (31095):             "address": "\u4e2d\u5929\u8def1\u53f7",
I/flutter (31095):             "id": "1",
I/flutter (31095):             "name": "\u7ad9\u70b91"
I/flutter (31095):         },
I/flutter (31095):         {
I/flutter (31095):             "isSelect": false,
I/flutter (31095):             "address": "\u4e2d\u5929\u8def2\u53f7",
I/flutter (31095):             "id": "2",
I/flutter (31095):             "name": "\u7ad9\u70b92"
I/flutter (31095):         },
I/flutter (31095):         {
I/flutter (31095):             "isSelect": false,
I/flutter (31095):             "address": "\u4e2d\u5929\u8def3\u53f7",
I/flutter (31095):             "id": "3",
I/flutter (31095):             "name": "\u7ad9\u70b93"
I/flutter (31095):         },
I/flutter (31095):         {
I/flutter (31095):             "isSelect": false,
I/flutter (31095):             "address": "\u4e2d\u5929\u8def4\u53f7",
I/flutter (31095):             "id": "4",
I/flutter (31095):             "name": "\u7ad9\u70b94"
I/flutter (31095):         },
I/flutter (31095):         {
I/flutter (31095):             "isSelect": false,
I/flutter (31095):             "address": "\u4e2d\u5929\u8def5\u53f7",
I/flutter (31095):             "id": "5",
I/flutter (31095):             "name": "\u7ad9\u70b95"
I/flutter (31095):         }
I/flutter (31095):     ]
I/flutter (31095): }
```
